### ISSUE TITLE
Map location

### ISSUE THREAD

**Issue by adityamookerjee** [zaichaopan/airbnb-map-search#2]
Hi!

When I run the app, the map renders on the left and clashes with the listing content.
![image](https://user-images.githubusercontent.com/25236239/64066724-37b9b980-cbd2-11e9-912a-4aed9c40b639.png)
Does it look like this for you?

**Comment by vesper8** [comment]
Same here.. fix is very easy though..

on line 44 of App.vue, replace

```
<div class="w-1/3 py-2 pr-4 fixed pin-r" :class="{'map-before': !showMap }">
```
by
```
<div class="w-1/3 py-2 pr-4 pin-r" :class="{'map-before': !showMap }">
```
